name: Vitest CI
on: [push]
jobs:
  vitest-run: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        run: npm install
      - name: Run vitest
        run: npm run test
